- ignore: {name: "Use infix"} # 2 hints
- ignore: {name: "Use let"} # 4 hints
- ignore: {name: "Use newtype instead of data"} # 4 hints
- ignore: {name: "Use print"} # 1 hint
- ignore: {name: "Redundant bracket Found"} # 1 hint
- ignore: {name: "Redundant $"} # 1 hint
